/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomenRouteImport } from './routes/women'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as MenRouteImport } from './routes/men'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KurthaRouteImport } from './routes/kurtha'
import { Route as JhumkaRouteImport } from './routes/jhumka'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FootwearRouteImport } from './routes/footwear'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const MenRoute = MenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KurthaRoute = KurthaRouteImport.update({
  id: '/kurtha',
  path: '/kurtha',
  getParentRoute: () => rootRouteImport,
} as any)
const JhumkaRoute = JhumkaRouteImport.update({
  id: '/jhumka',
  path: '/jhumka',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FootwearRoute = FootwearRouteImport.update({
  id: '/footwear',
  path: '/footwear',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/footwear': typeof FootwearRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jhumka': typeof JhumkaRoute
  '/kurtha': typeof KurthaRoute
  '/login': typeof LoginRoute
  '/men': typeof MenRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/stores': typeof StoresRoute
  '/stories': typeof StoriesRoute
  '/wishlist': typeof WishlistRoute
  '/women': typeof WomenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/cart': typeof CartRoute
  '/footwear': typeof FootwearRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jhumka': typeof JhumkaRoute
  '/kurtha': typeof KurthaRoute
  '/login': typeof LoginRoute
  '/men': typeof MenRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/stores': typeof StoresRoute
  '/stories': typeof StoriesRoute
  '/wishlist': typeof WishlistRoute
  '/women': typeof WomenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/footwear': typeof FootwearRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jhumka': typeof JhumkaRoute
  '/kurtha': typeof KurthaRoute
  '/login': typeof LoginRoute
  '/men': typeof MenRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/stores': typeof StoresRoute
  '/stories': typeof StoriesRoute
  '/wishlist': typeof WishlistRoute
  '/women': typeof WomenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/admin'
    | '/cart'
    | '/footwear'
    | '/forgot-password'
    | '/jhumka'
    | '/kurtha'
    | '/login'
    | '/men'
    | '/shop'
    | '/signup'
    | '/stores'
    | '/stories'
    | '/wishlist'
    | '/women'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/products/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/cart'
    | '/footwear'
    | '/forgot-password'
    | '/jhumka'
    | '/kurtha'
    | '/login'
    | '/men'
    | '/shop'
    | '/signup'
    | '/stores'
    | '/stories'
    | '/wishlist'
    | '/women'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/products/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/admin'
    | '/cart'
    | '/footwear'
    | '/forgot-password'
    | '/jhumka'
    | '/kurtha'
    | '/login'
    | '/men'
    | '/shop'
    | '/signup'
    | '/stores'
    | '/stories'
    | '/wishlist'
    | '/women'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/products/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  FootwearRoute: typeof FootwearRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JhumkaRoute: typeof JhumkaRoute
  KurthaRoute: typeof KurthaRoute
  LoginRoute: typeof LoginRoute
  MenRoute: typeof MenRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  StoresRoute: typeof StoresRoute
  StoriesRoute: typeof StoriesRoute
  WishlistRoute: typeof WishlistRoute
  WomenRoute: typeof WomenRoute
  ProductsIdRoute: typeof ProductsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men': {
      id: '/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof MenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurtha': {
      id: '/kurtha'
      path: '/kurtha'
      fullPath: '/kurtha'
      preLoaderRoute: typeof KurthaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jhumka': {
      id: '/jhumka'
      path: '/jhumka'
      fullPath: '/jhumka'
      preLoaderRoute: typeof JhumkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footwear': {
      id: '/footwear'
      path: '/footwear'
      fullPath: '/footwear'
      preLoaderRoute: typeof FootwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  FootwearRoute: FootwearRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JhumkaRoute: JhumkaRoute,
  KurthaRoute: KurthaRoute,
  LoginRoute: LoginRoute,
  MenRoute: MenRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  StoresRoute: StoresRoute,
  StoriesRoute: StoriesRoute,
  WishlistRoute: WishlistRoute,
  WomenRoute: WomenRoute,
  ProductsIdRoute: ProductsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
